name: Deploy to Hetzner Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: TimDaub/hetzner-cloud-deploy-server-action@v2
        with:
          server-name: "ubuntu-fushop-unique"  # Koristi jedinstveno ime
          server-image: "ubuntu-20.04"
          server-type: "cx32"
          ssh-key-name: "fushopkey"
          hcloud-token: ${{ secrets.HCLOUD_TOKEN }}
          delete-server: false       # ili true, ako želiš da brišeš prethodni server
          startup-timeout: 40000
