name: Deploy to Hetzner

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Postavite na odgovarajuću verziju .NET 8 SDK-a

      - name: Restore NuGet packages
        run: dotnet restore FUshop.API.sln

      - name: Build project
        run: dotnet build FUshop.API.sln --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish FUshop.API.sln --configuration Release --no-build --output ./publish

      - name: Deploy to Hetzner
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./publish/"
          target: "/var/www/fushop-api"
